services:
  digiconsinga_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digiconsinga_api
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./prisma:/app/prisma
    command: "npm run start"
