services:
  digicon_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digicon_api
    ports:
      - "3301:3301"
    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
    command: "node server.js"
